### ISSUE TITLE
Error when doing extract: OverflowError: Python integer out of bounds

### ISSUE THREAD

**Issue by ramirobarrantes** [tyjo/coptr#22]
I am doing coptr extract on a bam file and I am getting an error:

```
(coptr) ramirobarrantes@COM08018-2 coptr % coptr extract bams/ test/
coptr extract bams/ test/
[INFO] [Nov 07, 2024 16:20:04] [coptr.bam_processor] Processing bams/ERR10889327.bam.
Traceback (most recent call last):
  File "/Users/ramirobarrantes/.pyenv/versions/3.10.6/bin/coptr", line 8, in <module>
    sys.exit(cli())
  File "/Users/ramirobarrantes/.pyenv/versions/3.10.6/lib/python3.10/site-packages/coptr/cli.py", line 576, in cli
    ProgramOptions()
  File "/Users/ramirobarrantes/.pyenv/versions/3.10.6/lib/python3.10/site-packages/coptr/cli.py", line 70, in __init\
__
    getattr(self, args.command)()
  File "/Users/ramirobarrantes/.pyenv/versions/3.10.6/lib/python3.10/site-packages/coptr/cli.py", line 240, in extract
    coverage_maps = bam_processor.process_bam(fpath, args.bt2_k)
  File "/Users/ramirobarrantes/.pyenv/versions/3.10.6/lib/python3.10/site-packages/coptr/bam_processor.py", line 509, in process_bam
    reads, lengths = self.extract_reads(bam_file)
  File "/Users/ramirobarrantes/.pyenv/versions/3.10.6/lib/python3.10/site-packages/coptr/bam_processor.py", line 269, in extract_reads
    read_container.check_add_mapping(read_name, ref_name, pos, alignment_score)
  File "/Users/ramirobarrantes/.pyenv/versions/3.10.6/lib/python3.10/site-packages/coptr/bam_processor.py", line 98, in check_add_mapping
    self.read_data[self.next_row_idx][2] = score
OverflowError: Python integer -30 out of bounds for uint32
```

Any suggestions?

**Comment by ramirobarrantes** [comment]
Solved!! I had the  wrong numpy version.
